import type { Metadata } from "next";
import "./globals.css";
import { Alert } from "@/components/ui";
import { FilteredResultsModal } from "@/components/products";


export const metadata: Metadata = {
  title: "Prueba técnica",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased overflow-hidden`}>
        <Alert />
        <FilteredResultsModal />
        {children}
      </body>
    </html>
  );
}
